[2021-11-25 13:01:53,711: INFO: 01_base_model_creation]: 
********************
[2021-11-25 13:01:53,712: INFO: 01_base_model_creation]: >>>>> stage creating base model started <<<<<
[2021-11-25 13:01:53,712: ERROR: 01_base_model_creation]: main() missing 1 required positional argument: 'params_path'
Traceback (most recent call last):
  File "src/01_base_model_creation.py", line 34, in <module>
    main(config_path=parsed_args.config)
TypeError: main() missing 1 required positional argument: 'params_path'
[2021-11-25 13:04:17,130: INFO: 01_base_model_creation]: 
********************
[2021-11-25 13:04:17,130: INFO: 01_base_model_creation]: >>>>> stage creating base model started <<<<<
[2021-11-25 13:04:17,130: ERROR: 01_base_model_creation]: main() missing 1 required positional argument: 'params_path'
Traceback (most recent call last):
  File "src/01_base_model_creation.py", line 66, in <module>
    main(config_path=parsed_args.config)
TypeError: main() missing 1 required positional argument: 'params_path'
[2021-11-25 13:04:46,509: INFO: 01_base_model_creation]: 
********************
[2021-11-25 13:04:46,509: INFO: 01_base_model_creation]: >>>>> stage creating base model started <<<<<
[2021-11-25 13:04:46,510: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2021-11-25 13:04:52,129: INFO: 01_base_model_creation]: >>>>> stage creating base model completed!<<<<<

[2021-11-25 13:18:35,056: INFO: 01_base_model_creation]: 
********************
[2021-11-25 13:18:35,057: INFO: 01_base_model_creation]: >>>>> stage creating base model started <<<<<
[2021-11-25 13:18:35,058: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2021-11-25 13:18:35,414: ERROR: 01_base_model_creation]: module 'tensorflow.keras.layers' has no attribute 'Relu'
Traceback (most recent call last):
  File "src/01_base_model_creation.py", line 66, in <module>
    main(config_path=parsed_args.config)
  File "src/01_base_model_creation.py", line 40, in main
    tf.keras.layers.Relu(), ## alternative way
AttributeError: module 'tensorflow.keras.layers' has no attribute 'Relu'
[2021-11-25 13:19:15,925: INFO: 01_base_model_creation]: 
********************
[2021-11-25 13:19:15,926: INFO: 01_base_model_creation]: >>>>> stage creating base model started <<<<<
[2021-11-25 13:19:15,927: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2021-11-25 13:19:16,354: ERROR: 01_base_model_creation]: module 'tensorflow.keras.layers' has no attribute 'sigmoid'
Traceback (most recent call last):
  File "src/01_base_model_creation.py", line 66, in <module>
    main(config_path=parsed_args.config)
  File "src/01_base_model_creation.py", line 40, in main
    tf.keras.layers.sigmoid(), ## alternative way
AttributeError: module 'tensorflow.keras.layers' has no attribute 'sigmoid'
[2021-11-25 13:19:47,438: INFO: 01_base_model_creation]: 
********************
[2021-11-25 13:19:47,438: INFO: 01_base_model_creation]: >>>>> stage creating base model started <<<<<
[2021-11-25 13:19:47,439: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2021-11-25 13:19:47,847: ERROR: 01_base_model_creation]: module 'tensorflow.keras.layers' has no attribute 'sigmoid'
Traceback (most recent call last):
  File "src/01_base_model_creation.py", line 66, in <module>
    main(config_path=parsed_args.config)
  File "src/01_base_model_creation.py", line 40, in main
    tf.keras.layers.sigmoid(), ## alternative way
AttributeError: module 'tensorflow.keras.layers' has no attribute 'sigmoid'
[2021-11-25 13:19:58,917: INFO: 01_base_model_creation]: 
********************
[2021-11-25 13:19:58,918: INFO: 01_base_model_creation]: >>>>> stage creating base model started <<<<<
[2021-11-25 13:19:58,919: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2021-11-25 13:19:59,301: ERROR: 01_base_model_creation]: module 'tensorflow.keras.layers' has no attribute 'sigmoid'
Traceback (most recent call last):
  File "src/01_base_model_creation.py", line 66, in <module>
    main(config_path=parsed_args.config)
  File "src/01_base_model_creation.py", line 40, in main
    tf.keras.layers.sigmoid(), ## alternative way
AttributeError: module 'tensorflow.keras.layers' has no attribute 'sigmoid'
[2021-11-25 13:20:32,398: INFO: 01_base_model_creation]: 
********************
[2021-11-25 13:20:32,399: INFO: 01_base_model_creation]: >>>>> stage creating base model started <<<<<
[2021-11-25 13:20:32,400: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2021-11-25 13:20:37,525: INFO: 01_base_model_creation]: >>>>> stage creating base model completed!<<<<<

[2021-11-25 14:40:27,147: INFO: 01_base_model_creation]: 
********************
[2021-11-25 14:40:27,148: INFO: 01_base_model_creation]: >>>>> stage creating base model started <<<<<
[2021-11-25 14:40:27,149: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2021-11-25 14:41:03,964: ERROR: 01_base_model_creation]: in user code:

    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\training.py:855 train_function  *
        return step_function(self, iterator)
    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\training.py:845 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\distribute\distribute_lib.py:1285 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\distribute\distribute_lib.py:2833 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\distribute\distribute_lib.py:3608 _call_for_each_replica
        return fn(*args, **kwargs)
    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\training.py:838 run_step  **
        outputs = model.train_step(data)
    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\training.py:797 train_step
        y, y_pred, sample_weight, regularization_losses=self.losses)
    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\compile_utils.py:187 __call__
        self.build(y_pred)
    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\compile_utils.py:136 build
        self._losses = nest.map_structure(self._get_loss_object, self._losses)
    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\util\nest.py:867 map_structure
        structure[0], [func(*x) for x in entries],
    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\util\nest.py:867 <listcomp>
        structure[0], [func(*x) for x in entries],
    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\compile_utils.py:276 _get_loss_object
        loss = losses_mod.get(loss)
    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\losses.py:2078 get
        return deserialize(identifier)
    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\losses.py:2037 deserialize
        printable_module_name='loss function')
    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\utils\generic_utils.py:703 deserialize_keras_object
        .format(printable_module_name, object_name))

    ValueError: Unknown loss function: LOSS. Please ensure this object is passed to the `custom_objects` argument. See https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details.
Traceback (most recent call last):
  File "src/01_base_model_creation.py", line 81, in <module>
    main(config_path=parsed_args.config)
  File "src/01_base_model_creation.py", line 59, in main
    history = model.fit(X_train, y_train,epochs=10,validation_data=(X_valid,y_valid),verbose=2)
  File "C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\training.py", line 1183, in fit
    tmp_logs = self.train_function(iterator)
  File "C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\eager\def_function.py", line 889, in __call__
    result = self._call(*args, **kwds)
  File "C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\eager\def_function.py", line 933, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\eager\def_function.py", line 764, in _initialize
    *args, **kwds))
  File "C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\eager\function.py", line 3050, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\eager\function.py", line 3444, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\eager\function.py", line 3289, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\framework\func_graph.py", line 999, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\eager\def_function.py", line 672, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\framework\func_graph.py", line 986, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\training.py:855 train_function  *
        return step_function(self, iterator)
    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\training.py:845 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\distribute\distribute_lib.py:1285 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\distribute\distribute_lib.py:2833 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\distribute\distribute_lib.py:3608 _call_for_each_replica
        return fn(*args, **kwargs)
    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\training.py:838 run_step  **
        outputs = model.train_step(data)
    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\training.py:797 train_step
        y, y_pred, sample_weight, regularization_losses=self.losses)
    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\compile_utils.py:187 __call__
        self.build(y_pred)
    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\compile_utils.py:136 build
        self._losses = nest.map_structure(self._get_loss_object, self._losses)
    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\util\nest.py:867 map_structure
        structure[0], [func(*x) for x in entries],
    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\util\nest.py:867 <listcomp>
        structure[0], [func(*x) for x in entries],
    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\compile_utils.py:276 _get_loss_object
        loss = losses_mod.get(loss)
    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\losses.py:2078 get
        return deserialize(identifier)
    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\losses.py:2037 deserialize
        printable_module_name='loss function')
    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\utils\generic_utils.py:703 deserialize_keras_object
        .format(printable_module_name, object_name))

    ValueError: Unknown loss function: LOSS. Please ensure this object is passed to the `custom_objects` argument. See https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details.

[2021-11-25 14:44:15,414: INFO: 01_base_model_creation]: 
********************
[2021-11-25 14:44:15,415: INFO: 01_base_model_creation]: >>>>> stage creating base model started <<<<<
[2021-11-25 14:44:15,416: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2021-11-25 14:44:18,018: ERROR: 01_base_model_creation]: in user code:

    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\training.py:855 train_function  *
        return step_function(self, iterator)
    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\training.py:845 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\distribute\distribute_lib.py:1285 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\distribute\distribute_lib.py:2833 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\distribute\distribute_lib.py:3608 _call_for_each_replica
        return fn(*args, **kwargs)
    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\training.py:838 run_step  **
        outputs = model.train_step(data)
    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\training.py:797 train_step
        y, y_pred, sample_weight, regularization_losses=self.losses)
    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\compile_utils.py:187 __call__
        self.build(y_pred)
    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\compile_utils.py:136 build
        self._losses = nest.map_structure(self._get_loss_object, self._losses)
    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\util\nest.py:867 map_structure
        structure[0], [func(*x) for x in entries],
    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\util\nest.py:867 <listcomp>
        structure[0], [func(*x) for x in entries],
    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\compile_utils.py:276 _get_loss_object
        loss = losses_mod.get(loss)
    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\losses.py:2078 get
        return deserialize(identifier)
    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\losses.py:2037 deserialize
        printable_module_name='loss function')
    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\utils\generic_utils.py:703 deserialize_keras_object
        .format(printable_module_name, object_name))

    ValueError: Unknown loss function: LOSS. Please ensure this object is passed to the `custom_objects` argument. See https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details.
Traceback (most recent call last):
  File "src/01_base_model_creation.py", line 85, in <module>
    main(config_path=parsed_args.config)
  File "src/01_base_model_creation.py", line 63, in main
    verbose=2)
  File "C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\training.py", line 1183, in fit
    tmp_logs = self.train_function(iterator)
  File "C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\eager\def_function.py", line 889, in __call__
    result = self._call(*args, **kwds)
  File "C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\eager\def_function.py", line 933, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\eager\def_function.py", line 764, in _initialize
    *args, **kwds))
  File "C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\eager\function.py", line 3050, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\eager\function.py", line 3444, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\eager\function.py", line 3289, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\framework\func_graph.py", line 999, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\eager\def_function.py", line 672, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\framework\func_graph.py", line 986, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\training.py:855 train_function  *
        return step_function(self, iterator)
    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\training.py:845 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\distribute\distribute_lib.py:1285 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\distribute\distribute_lib.py:2833 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\distribute\distribute_lib.py:3608 _call_for_each_replica
        return fn(*args, **kwargs)
    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\training.py:838 run_step  **
        outputs = model.train_step(data)
    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\training.py:797 train_step
        y, y_pred, sample_weight, regularization_losses=self.losses)
    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\compile_utils.py:187 __call__
        self.build(y_pred)
    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\compile_utils.py:136 build
        self._losses = nest.map_structure(self._get_loss_object, self._losses)
    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\util\nest.py:867 map_structure
        structure[0], [func(*x) for x in entries],
    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\util\nest.py:867 <listcomp>
        structure[0], [func(*x) for x in entries],
    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\compile_utils.py:276 _get_loss_object
        loss = losses_mod.get(loss)
    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\losses.py:2078 get
        return deserialize(identifier)
    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\losses.py:2037 deserialize
        printable_module_name='loss function')
    C:\Users\shara\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\utils\generic_utils.py:703 deserialize_keras_object
        .format(printable_module_name, object_name))

    ValueError: Unknown loss function: LOSS. Please ensure this object is passed to the `custom_objects` argument. See https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details.

[2021-11-25 14:49:06,121: INFO: 01_base_model_creation]: 
********************
[2021-11-25 14:49:06,122: INFO: 01_base_model_creation]: >>>>> stage creating base model started <<<<<
[2021-11-25 14:49:06,123: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2021-11-25 14:49:52,701: INFO: common]: created directory at: artifacts\models
[2021-11-25 14:49:52,756: INFO: 01_base_model_creation]: base model is saved at artifacts\models\base_model.h5
[2021-11-25 14:49:52,794: INFO: 01_base_model_creation]: >>>>> stage creating base model completed!<<<<<

[2021-11-25 15:06:33,161: INFO: 01_base_model_creation]: 
********************
[2021-11-25 15:06:33,162: INFO: 01_base_model_creation]: >>>>> stage creating base model started <<<<<
[2021-11-25 15:06:33,163: INFO: common]: yaml file: configs/config.yaml loaded successfully
[2021-11-25 15:07:16,090: INFO: common]: created directory at: artifacts\models
[2021-11-25 15:07:16,136: INFO: 01_base_model_creation]: base model is saved at artifacts\models\base_model.h5
[2021-11-25 15:07:16,990: INFO: 01_base_model_creation]: evaluation metrics [0.3162641227245331, 0.9092000126838684]
[2021-11-25 15:07:17,033: INFO: 01_base_model_creation]: >>>>> stage creating base model completed!<<<<<

